# Generated by Django 4.2.13 on 2024-07-04 22:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0001_initial'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='writer',
        ),

        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=django.db.models.deletion.CASCADE),
            preserve_default=False,  # 기본값 설정 삭제
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='upload_filepath'),  # upload_to 수정
        ),
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=models.CharField(max_length=20, choices=[
                ('happy', '행복'),
                ('sad', '슬픔'),
                ('angry', '분노'),
                ('depression', '우울'),
            ]),
        ),
    ]


