# Generated by Django 4.2.13 on 2024-07-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0003_alter_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='position',
            field=models.TextField(default='친구'),
        ),
    ]
