# Generated by Django 4.2.13 on 2024-07-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0004_alter_article_keyword_alter_article_keyword2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
