# Generated by Django 4.2.13 on 2024-07-04 22:45

import articleapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0005_alter_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=articleapp.models.upload_filepath),
        ),
    ]
