# Generated by Django 4.2.13 on 2024-07-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0006_alter_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='article',
            name='share',
        ),
    ]
