# Generated by Django 4.2.13 on 2024-07-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0007_remove_article_last_modified_remove_article_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='position',
        ),
        migrations.AddField(
            model_name='article',
            name='position1',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='position2',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='position3',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=models.CharField(choices=[('family', '가족'), ('friend', '지인'), ('superior', '직장상사'), ('etc', '기타')], max_length=20),
        ),
    ]
