# Generated by Django 4.2.13 on 2024-07-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0008_remove_article_position_article_position1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='position1',
            new_name='position',
        ),
    ]
