# Generated by Django 4.2.13 on 2024-07-05 17:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='project',
            name='share',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='writer',
        ),
        migrations.AddField(
            model_name='project',
            name='keyword2',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='keyword3',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.TextField(default=datetime.datetime(2024, 7, 5, 17, 11, 29, 928376, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.CharField(choices=[('family', '가족'), ('friend', '지인'), ('superior', '직장상사'), ('etc', '기타')], default=datetime.datetime(2024, 7, 5, 17, 11, 43, 581943, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='keyword',
            field=models.TextField(max_length=20),
        ),
    ]
