# Generated by Django 5.0.6 on 2024-07-02 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0001_initial'),
        ('cards', '0003_alter_card_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='selected_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='articleapp.article'),
        ),
    ]
