# Generated by Django 5.0.6 on 2024-06-29 02:20

import cards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('job', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=cards.models.upload_filepath)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CardKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_cardkeyword', to='cards.card')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keywords_cardkeyword', to='cards.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='keyword',
            field=models.ManyToManyField(related_name='cards', through='cards.CardKeyword', to='cards.keyword'),
        ),
    ]
