# Generated by Django 4.2.13 on 2024-06-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_project_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='project',
            field=models.CharField(default=2, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
